# FROM node:12-alpine

# WORKDIR /var/server

# COPY . .

# RUN yarn install

# CMD [ "yarn" , "mern"]

#  Dockerfile for Node Express Backend

FROM node:10.16-alpine

# Create App Directory
WORKDIR /usr/src/app

# Install Dependencies
COPY . .

RUN npm install


# Exports
EXPOSE 5000

CMD ["npm","start"]