apiVersion: v1
kind: Service
metadata:
  name: service-client
  namespace: medikura
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000