apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: medikura
  labels:
    app: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: mern-client
        image: houssi/mern-client:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name : regcred
