apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: medikura
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mern-db
        image: houssi/mern-db:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name : regcred
