apiVersion: v1
kind: Service
metadata:
  name: service-server
  namespace: medikura
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
