#  Dockerfile for Node Express Backend

FROM node:10.16-alpine

# Create App Directory
WORKDIR /usr/src/app


COPY package*.json ./

# Install Dependencies
RUN npm install

# copy local files to app folder
COPY . .

# Exports
EXPOSE 5000

CMD ["npm","start"]